services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-volumes:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    networks:
      - app-network

  laravel-app:
    build:
      context: ./docker/php
    container_name: laravel-app
    volumes:
      - .:/home/source/main
    working_dir: /home/source/main
    networks:
      - app-network

  nginx:
    build:
      context: ./docker/nginx
    container_name: todo-nginx
    ports:
      - "8000:80"
    depends_on:
      - laravel-app
    volumes:
      - .:/home/source/main
    networks:
      - app-network

volumes:
  mysql-volumes:
    driver: local
networks:
  app-network:
    driver: bridge